### ISSUE TITLE
refactor: use auto generate mocks

### ISSUE THREAD

**Issue by StewartJingga** [odpf/columbus#26]
**Is your feature request related to a problem? Please describe.**
Current meteor are still using manually generated mocks and creating a new mock could take some effort that can be easily avoided using auto generated mocks.

**Describe the solution you'd like**
Use testify/mockery to auto generate mocks.

**Comment by mabdh** [comment]
@ravisuhag we are already autogenerate the mock using `mockery`, any other concern we reopened this ticket?

**Comment by ravisuhag** [comment]
It was unintentional. Closing it.
