### ISSUE TITLE
feat(discovery): boost score using resource fields

### ISSUE THREAD

**Issue by StewartJingga** [odpf/columbus#28]
**Is your feature request related to a problem? Please describe.**
I have a field in my resources called `total_usage` as integer. I want these resources with higher `total_usage` value to have higher score so it will show on top level page when searching via `/v1/search`.

**Describe the solution you'd like**
Allow boosting score using fields on the resource in Search API (`/v1/search`).

**Comment by mabdh** [comment]
Duplicated #31
