### ISSUE TITLE
feat(discovery): search based on user's past behaviour (table usage)

### ISSUE THREAD

**Issue by mabdh** [odpf/columbus#31]
**Is your feature request related to a problem? Please describe.**
I want to be able to search based on user's past behaviour (table usage). The more table is being. used, the more relevant it is shown in the search results.

**Describe the solution you'd like**
Counting in table usage in relevancy only makes sense if we are searching in `table` type context. Therefore, this feature only works in `table` index/resource and wouldn't apply in universal/global context (where we search in all indices).

Basically, there are 2 possible implementation details to consider table usage in the relevancy parameter: implicit or explicit.

_Implicit_
Everytime users search within `table` index, we always consider table usage as part of relevancy (e.g. always count it as boosting value)

_Explicit_
We could give user control whether they want to count table usage as the relevancy or not everytime users search within `table` index by adding more param (query param) in Search API. The new query param could be called as ~~`sortby`~~ `rankby` with value `usage`

**Proposed Decision**
For now, we could go with the _Explicit_ one. We could give user control whether they want to count table usage as the relevancy.

**Comment by StewartJingga** [comment]
@mabdh 
if we go with implicit, we may need to hardcode `table` type into Columbus 🤔 , until we actually sure we want `table` type to be a known domain model/context in Columbus then it would be too hacky at this point.

The explicit one is pretty good since it would also allow generic sorting on search.

**Comment by mabdh** [comment]
Since we went with `explicit` approach. Now I think again that a new query param called `sortby` might feel not intuitive because `sort` could be ascendingly or descendingly.

I am thinking maybe better to name the query param as `rankby`. IMO, it is more intuitive for a term `rank` to prioritize based on specific field.

wdyt @StewartJingga @ravisuhag ?

**Comment by mabdh** [comment]
We will go with query param `rankby` as it is make more sense in terms of how we do scoring in our search results.
