### ISSUE TITLE
feat(discovery): auto suggestion (search-as-you-type) on search

### ISSUE THREAD

**Issue by mabdh** [odpf/columbus#33]
**Is your feature request related to a problem? Please describe.**
I want columbus to support auto suggestions (search as you type)

**Describe the solution you'd like**

Here we are separating the problem into two: `API Changes` and `Search Logic`

### Approach 1
Define a new API 
```
/suggestion/?text=<text>
```` 
and return list of suggested list of data with fields: `urn`, `name`, `type`, and `service`. 

### Approach 2
Use existing search API with a new boolean query param called `suggestion`
```
/search/?text=<text>&suggestion=true
````
Columbus will return list of suggested list of data with fields: `urn`, `name`, `type`, and `service` if `suggestion=true`, else will return the search results as it is

## Search Logic

Search logic for suggestion will impact how relevant are our suggestions. In this case, it is flexible to decide which one should we pick as for now, we could optimize and iterate it later. [Reference](https://stackoverflow.com/a/42130711).

### Approach 1
[Term suggester](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html#term-suggester). The one that provides "similar" term, based on the edit distance. It provides suggestions based on data in the index, there are a lot of knobs and turns to tune it.

### Approach 2
[Phrase suggester](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html#phrase-suggester). It's very similar to what term suggester is doing, but taking into account a whole phrase.

### Approach 3
[Completion suggester](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html#completion-suggester) or search-as-you-type functionality. If first two are doing something like did you mean functionality or spellchecking, based on the actual terms in the index. This one should "show" you some 5 or 10 relevant docs, while user is typing, and for this one you need to manually index field of suggestion type, where later ES will do a fast lookup.

### Approach 4
[Context suggester](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html#context-suggester). This one is a continuation of the completion suggester, with the idea of the some context where user is coming from (geo) or if engine wants to boost some company over another, just because they are paid for it, or something like this. In this case you also need to manually index additional data.

**Proposed Approach**

- Approach 2 for API changes. Adding new query param would be simpler to deliver as for now. We can make the default to false.
- Approach 2 for Search Logic. Phrase suggester will capture a whole text in a field and not just a single term/word. This one is simpler than context/complete suggester and we could improve on this going forward.

**Comment by StewartJingga** [comment]
@mabdh 
For API changes, Im thinking about having a new API (approach 1) just because the response payload would be different and it would be confusing if the same API returns 2 different kind of payload. wdyt?

for Search Logic, may need more users' perspective. which suggester do you think would be beneficial to users at this point? 
I personally would say go with the easiest one first unless there is a specific needs on suggestion type.

wdyt? @ravisuhag

**Comment by mabdh** [comment]
Okay, let's go for the Approach 1 with new API changes.

**Comment by ravisuhag** [comment]
For the new API approach, I think `/suggest` will  be better.

**Comment by StewartJingga** [comment]
@ravisuhag wdyt about which suggester to use? from me I'm still not sure which one would benefit users most at this time and we should start with the simplest approach first.

**Comment by ravisuhag** [comment]
+1 on starting with the simplest approach (minimum on latency) until we get user feedback.

**Comment by mabdh** [comment]
@StewartJingga On a side note, Approach 3 might be suitable with what we need but that requires a special `suggestion` field that needs to be field during index time. The suggestion will only consider that `suggestion` field so it can look up faster. 

Either Approach 1 or 2 are the simplest, you can do quick comparison on that. AFAIK, Approach 2 would be more suitable for our use case.

**Comment by StewartJingga** [comment]
Let's go with Approach 2 first because It can do what approach 1 does and can be extended further with configs, analyzers and mapping (this one we may not use it in the early stage).

wdyt? @mabdh @ravisuhag
