### ISSUE TITLE
feat: discussion feature

### ISSUE THREAD

**Issue by StewartJingga** [odpf/columbus#47]
**Is your feature request related to a problem? Please describe.**
I want to create issues on a resource so that other users can see it.

**Describe the solution you'd like**
1. CRUD Issue apis for a resource

**Comment by mabdh** [comment]
## Use cases
**Discussion**

- Create a discussion
- Get a discussion (filter by asset)
- List discussion (filter by asset)
- Update a discussion
- Upvote discussion (out of scope)
- Pinning/Unpinning discussions (out of scope)

**Discussion Comments**

- List discussion comments
- Get a discussion comment
- Create discussion comment
- Update discussion comment
- Delete discussion comment
- Upvote discussion comment (out of scope)

**Discussion Labels**

- List labels of a discussion 

**Users' Discussions**

- List assigned discussion of a user
---
With use cases mentioned above, we could generalize it into discussions by defining it into multiple types. 

**Discussion Property**

- Title
- Body
- State
- Assignees (nullable, array of string)
- Assets (nullable, array of string)
- Owner (not null)
- Labels (nullable, array of string)
- Type (int)

**Discussion Types**

-   Issues
  -   states
    -   Unknown: enum 0
    -   Open: enum 1
    -   Closed: enum 2
-   Q&A
  -   states
    -   Unknown: enum 0
    -   Unanswered: enum 1
    -   Answered: enum 2
  -   Comments can be marked as an `answer`  (out of scope)
  -   Suggest answer (out of scope)
  -   Vote best answer (out of scope)
-   Open-ended questions
  -   No states

**Users discussion**

- Return discussion in user context
- Owned, assigned

**Comments**

- Comment belongs to the discussion
- Discussion could have multiple comments
- Comments could have replies which is another comments (out of scope)
- Reply comment could not be upvoted (out of scope)
