### ISSUE TITLE
remove gorm library

### ISSUE THREAD

**Issue by StewartJingga** [odpf/columbus#52]
**Is your feature request related to a problem? Please describe.**
Currently we are using [GORM](https://gorm.io/index.html) for:
1. ORM
2. Database Migration

It works fine at the moment, but right now we are depending on GORM auto migrate for db migration and if in the future we want to change our postgres client, it would harder to switch, especially if we have lots of table to migrate.

**Describe the solution you'd like**
For Database Migration, we can use https://github.com/golang-migrate/migrate
For ORM, we can use simple https://github.com/jmoiron/sqlx as it is a dedicated postgres client and https://github.com/jackc/pgx as its driver

**Comment by mabdh** [comment]
In addition to that, GORM is good but there are some edge cases that it does not cover yet. Since our use cases are still evolving, it is better for us to use the more flexible DB library.
