### ISSUE TITLE
feat: add starring repository 

### ISSUE THREAD

**Issue by mabdh** [odpf/columbus#59]
**Is your feature request related to a problem? Please describe.**
I want to star/bookmark a resource to be revisited again later and able to fetch all of my starred resources.

**Describe the solution you'd like**
- We need a new table in DB with this schema

|starring | type| Sample Value|
|-- | --|--|
|id (PK) | SERIAL | 1|
|user_id (FK) | UUID | 11234-4214214|
|asset_id (FK) | UUID | 11234-4214214|
|created_at | TIMESTAMP | 12345667|
|updated_at | TIMESTAMP | 12345667|

- We need a new starring repository layer

**Comment by mabdh** [comment]
Considering we already have assets table in postgres, do you guys think it will be better to remove `asset_urn` and `asset_type` and replace them with `asset_id` instead? @StewartJingga @ravisuhag

**Comment by ravisuhag** [comment]
assets_urn would still need to be there, right? That is the only way meteor identifies the assets, right. Without this, It won't know about Columbus asset_id to update assets.
