### ISSUE TITLE
feat: user/discussions API

### ISSUE THREAD

**Issue by mabdh** [odpf/columbus#85]
**Is your feature request related to a problem? Please describe.**
Discussions feature is already implemented in #47 , we need to add users API that list down all discussions related with specific user (recognized by User email header)

**Describe the solution you'd like**
- Add user's discussions API `/user/discussions`

**Comment by ravisuhag** [comment]
@mabdh Will this mean all discussions that the user created?
Also, I assume discussions APIs will be something like `/discussions` If that is the case do we need API specific to users or can discussions related to a user can be returned by a param in `/discussions` api?

**Comment by mabdh** [comment]
@ravisuhag yes, could be `assigned` or `created/owned` by the user. The route will be `/user/discussions?filter=assigned`.

The behaviour should be similar with `/discussions?owner=1234-5678` or `/discussions?assignee=1234-5678`

This is similar with `/user/starred` where we have that api and other api that have the same behaviour `/users/{user_id}/starred`. 

Since both have the same features, it is possible to not doing the `/user/discussions` at the moment.

**Comment by ravisuhag** [comment]
I think it make sense. Let's go with it.
