### ISSUE TITLE
feat: add filtering in assets api

### ISSUE THREAD

**Issue by scortier** [odpf/columbus#88]
Is your feature request related to a problem? Please describe.
Pagination feature is already implemented in v1beta1 assets api , but filtering by certain fields are still not available.

Describe the solution you'd like
Add filtering by certain fields by handling columbus data in structured way.
- filter by types
- filter by services
- filter by field in asset.data
- querying by field ( includes by name , urn)
- sort by certain fields asc , desc
- size to fetch 
- offset

**Comment by scortier** [comment]
## Approaches :
### filter by types - 
- type - table,job,dashboard,topic
- services - all extractors 
- Querystring
   - `filter.type=tables&filter.services=mysql,postgres`
   - `filter.type=tables`  (display all metadata of type tables)

### filter by services - 
- QueryString 
   - `filter.service=presto` (querying only specific service)

### Sort by certain fields 
There can be two ways to implement it : 
1. Fields - 
    - SortBy -`query.Get("sort"),`
    - SortDirection - `query.Get("direction"),`
   
- fields in filter struct will look like this 
SortBy        string `json:"sort" validate:"omitempty,typeof=id created_at name"`
SortDirection string `json:"direction" validate:"omitempty,typeof=asc desc"`

- QueryString : `sort=name&direction=asc`

2. Field - 
    - Sort - `query.Get("sort")`
QueryString : `sort=name.asc`  (field.orderDirection)

### querying by field ( includes by name , urn)
Some of the ways to implement it - 
1. Recursive approach

```
func Filter(collection []string, f func(string) bool) []string {
    finalOutput := make([]string, 0)
    for _, v := range collection {
        if f(v) {
            finalOutput = append(finalOutput, v)
        }
    }
    return finalOutput
}

var strs = []string{"table1", "table2", "table3", "table_testing", "table_testfor", "_table"}

fmt.Println(Filter(strs, func(v string) bool {
	return strings.HasPrefix(v, "table_") // return table_testfor, table_testing
}))
```
2. Filtering using Graphql - Looking into it 

### filter by field in asset.data
Pending

### Size and Offset 
Already Implemented in assets api

**Comment by scortier** [comment]
@ravisuhag @StewartJingga @mabdh please have a look over the approaches , drop your feedbacks or suggestions , if any. Will keep updating further approaches too .

**Comment by mabdh** [comment]
- > querying by field ( includes by name , urn)

      can you please elaborate on this?


- For filter query params, rather than doing `?filter.type=tables&filter.services=mysql,postgres`, why not just `?`type=tables&services=mysql,postgres`?
- > json:"direction" validate:"omitempty,typeof=asc desc"
     can you please also elaborate on this? what does it mean by `validate` here? and what `typeof` means?

**Comment by mabdh** [comment]
@scortier Also, I think for this issue we could focus on HTTP API first

**Comment by scortier** [comment]
Query params finalized after discussion with @StewartJingga and @mabdh 

- `?name=asset_name&urn=some-urn` // filter by root asset field (exact match)
- `?data.dataset=booking&data.project=p-godata-id` // filter by nested data (exact match)
- `?q=internal&q_fields=name,data.layer,data.layer` // to query with a term from given fields (nested or not)
- `?sort=name&direction=desc` // to sort with single field and direction
- `?types=table,dashboard&services=bigquery,metabase` // to query multiple types or/and services

### Notes:
1. consider using Discovery feature (behind the scene) for [GET] /v1beta1/assets
