### ISSUE TITLE
feat: improve user information in columbus

### ISSUE THREAD

**Issue by mabdh** [odpf/columbus#90]
**Is your feature request related to a problem? Please describe.**
Currently we are relying on `email` for external identifier. External identifier will be used on API URL path param. Since `email` is a PII, it is not proper to pass it to path params.

**Describe the solution you'd like**
Instead of an `email`, we can rely on more generic information like `uuid`. We still collecting `email` in columbus but that is not a primary external user identifier. 

Changes needed are:
- User Repository
  - Migration file: add a new column called `uuid` with type `text` and nullable, and create an index for `uuid`
- User Service
  - Validation flow logic
    - Get uuid from user id header (required), Get email from user email header (required)
    - Check uuid in DB
      - if not exist, check if email exist
        - if exist, update uuid of the email
        - if not exist, create a new row
      - if exist, check if fetched email is empty
        - if empty, update email
        - if not empty, continue
- When Upserting Asset
  - insert asset owner (if not exist) to a new row in users table with null `uuid`
- Users API (api to look other users)
  - accept external uuid

**Comment by StewartJingga** [comment]
@mabdh @ravisuhag should we use `external_id` instead? uuid seems too locking and some users might have integer/username as the main identifier.

**Comment by ravisuhag** [comment]
@StewartJingga I think `uuid` is better than `external_id`. Agree that it might be username etc. But `external_id` seems very explicit. Which columbus doesn't really need to worry about.

**Comment by mabdh** [comment]
@StewartJingga I think `uuid` here is just a definition of `universally unique identifier` and we don't assume it has a `uuid` data type. Making the type as `string` would cover all scenarios regardless the data type that user already has.

**Comment by StewartJingga** [comment]
> @StewartJingga I think uuid is better than external_id. Agree that it might be username etc. But external_id seems very explicit. Which columbus doesn't really need to worry about.

Oh right yeah, it does not need to be `external_id` , but I'm just still wondering if `uuid` could be misleading or not.

> @StewartJingga I think `uuid` here is just a definition of `universally unique identifier` and we don't assume it has a `uuid` data type. Making the type as `string` would cover all scenarios regardless the data type that user already has.

`uuid` will always be string regardless from API side right? I'm just afraid when there is a `uuid` field, it could throw people off. But if you guys think it is pretty descriptive enough, then it should be fine.

**Comment by StewartJingga** [comment]
Also when we are referring to `user's uuid`, it would be ambiguous since our user id is also in `uuid` format.

**Comment by mabdh** [comment]
@StewartJingga yes it should always be string.

to avoid misunderstanding, we could add that definition in columbus documentation
