### ISSUE TITLE
feat: grpc interface

### ISSUE THREAD

**Issue by mabdh** [odpf/columbus#93]
**Is your feature request related to a problem? Please describe.**
We need to introduce a new `grpc` interface. The `grpc` interface could be used later by `cli` when we are building it.

**Describe the solution you'd like**
Approach should be discussed in this issue.

**Comment by mabdh** [comment]
For this,

- Create a proto 
- Create grpc server
- Create gRPC endpoints for these list of APIs
  - Assets
  - Discussions
    - Comments
  - Lineage
  - Tag Template
  - Users

Questions
  - Should we create the proto inside the repo first (before migrating it to `odpf/proton`) or just create that rightaway in the `odpf/proton`?
  - Should we use `grpc-gateway` or just create another grpc endpoint?

Is there any missing points? @StewartJingga @ravisuhag

**Comment by StewartJingga** [comment]
> Should we create the proto inside the repo first (before migrating it to odpf/proton) or just create that rightaway in the odpf/proton?

For ease of development, I'd suggest using it in the repo itself first.
In case we want to move it to `odpf/proton` we can just update it before merging.

> Should we use grpc-gateway or just create another grpc endpoint?

@rahmatrhd wdyt? I don't have much experience in this.

**Comment by ravisuhag** [comment]
We will create it in proton directly. 
We will use grpc-gateway for HTTP endpoints. You can refer to other ODPF services for the similar implementation.

**Comment by mabdh** [comment]
Let's just use grpc gateway to avoid overhead on creating grpc handlers? It also could generate swagger AFAIK

**Comment by mabdh** [comment]
@ravisuhag just saw your comment, sure will do

**Comment by rahmatrhd** [comment]
yes, agree, grpc-gateway is convenient to use and most of other services also use it already

**Comment by StewartJingga** [comment]
@mabdh also if im not mistaken, response from grpc is always gonna be a map/object. So we might need to wrap our array/list response to a field.

**Comment by mabdh** [comment]
It turns out there are a lot of API handlers that need to be migrated.

I am planning to divide this into multiple tickets.
1. Bootstrap grpc & grpc-gateway (serve it to the different port, for development only)
  - Migrate API handlers discussions & comments 
2. Migrate API handlers Users & Tag templates
3. Migrate API handlers Assets, Search, & Lineage
4. Remove old handlers, serve grpc through the main port (remove the old port), test all APIs

I will create issues for these

cc @StewartJingga @ravisuhag @rahmatrhd

**Comment by ravisuhag** [comment]
I think we can keep one issue and create multiple tasks in it. And PRs could be more than one.
