### ISSUE TITLE
Changing path of /user API to /me

### ISSUE THREAD

**Issue by mabdh** [odpf/columbus#95]
**Is your feature request related to a problem? Please describe.**
We currently have an API to get resources belong to a caller (user) with API `/v1beta1/user/starring` and `/v1beta1/user/discussions`.
But in [guardian](https://github.com/odpf/guardian) the API is `v1beta1/me`. I am thinking we can make it consistent across org by updating columbus API from `/user` to `/me`

**Describe the solution you'd like**
Updating columbus API from `/user` to `/me`

**Comment by mabdh** [comment]
any thought on this? @ravisuhag @StewartJingga @rahmatrhd

**Comment by StewartJingga** [comment]
I'm okay with that, I've always liked `/me` better than `/user`.

**Comment by rahmatrhd** [comment]
using `/me` at least can avoid confusion when we also manage `users` entity and expose it on `/users` (if we have). And I also like `/me` better than anything, pun intended 😜
